package fr.cg95.cvq.service.request.urbanism;

import fr.cg95.cvq.business.request.urbanism.*;
import fr.cg95.cvq.business.users.HomeFolder;
import fr.cg95.cvq.business.users.Adult;
import fr.cg95.cvq.testtool.TestUtils;

/**
 * Generated by Groovy only if not present, can be edited safely !
 */
public class ParkingSpaceReservationRequestFeeder {

    public static void feed(ParkingSpaceReservationRequest request) {
    }

	public static void setSubject(ParkingSpaceReservationRequest request,
	        String subjectPolicy, Adult requester, HomeFolder homeFolder) {
		
		TestUtils.feedRequestSubject(request, subjectPolicy, requester, homeFolder);
	}
}
